export function detectIntent(message) {
  const msg = message.toLowerCase();

  // ========================================
  // 1️⃣ KIỂM TRA TỪ KHÓA VỀ PHÒNG
  // ========================================
  const roomKeywords = [
    // Từ khóa cơ bản
    "phòng",
    "room",
    "giá phòng",
    "đặt phòng",
    "book",
    "booking",
    "reserve",
    "reservation",

    // Trạng thái phòng
    "available",
    "còn phòng",
    "phòng trống",
    "còn trống",
    "có phòng",
    "phòng còn",
    "full",
    "hết phòng",
    "sold out",

    // Loại phòng
    "loại phòng",
    "room type",
    "phòng đơn",
    "single",
    "phòng đôi",
    "double",
    "twin",
    "suite",
    "deluxe",
    "superior",
    "standard",
    "premium",
    "VIP",
    "executive",
    "family room",
    "phòng gia đình",
    "connecting room",
    "phòng liền kề",

    // View & vị trí phòng
    "view biển",
    "sea view",
    "ocean view",
    "view núi",
    "mountain view",
    "view thành phố",
    "city view",
    "view sông",
    "river view",
    "tầng cao",
    "high floor",
    "tầng thấp",
    "low floor",

    // Giường
    "giường đôi",
    "king bed",
    "queen bed",
    "giường đơn",
    "single bed",
    "twin bed",
    "2 giường",
    "giường phụ",
    "extra bed",
    "sofa bed",

    // Số người
    "1 người",
    "2 người",
    "3 người",
    "4 người",
    "couple",
    "cặp đôi",
    "gia đình",
    "family",
    "nhóm",
    "group",
    "đoàn",

    // Giá & chi phí
    "giá",
    "price",
    "cost",
    "bao nhiêu",
    "how much",
    "chi phí",
    "tiền phòng",
    "giá cả",
    "rate",
    "fee",
    "charge",
    "total",
    "tổng",
    "discount",
    "giảm giá",
    "promotion",
    "khuyến mãi",
    "deal",
    "offer",
    "package",
    "combo",

    // Hành động
    "thuê phòng",
    "rent",
    "check availability",
    "xem phòng",
    "tour phòng",
    "upgrade",
    "nâng cấp",
    "change room",
    "đổi phòng",
    "extend",
    "gia hạn",
  ];

  if (roomKeywords.some((keyword) => msg.includes(keyword))) {
    return "room";
  }

  // ========================================
  // 2️⃣ KIỂM TRA TỪ KHÓA VỀ ĐỊA ĐIỂM (SIÊU ĐẦY ĐỦ)
  // ========================================
  const nearbyKeywords = [
    // ===== CÂU HỎI PHỔ BIẾN =====
    "địa điểm",
    "place",
    "gần",
    "near",
    "nearby",
    "xung quanh",
    "around",
    "đi đâu",
    "where to go",
    "đi chơi",
    "chơi gì",
    "làm gì",
    "what to do",
    "ăn gì",
    "what to eat",
    "where to eat",
    "uống gì",
    "where to drink",
    "tham quan",
    "visit",
    "sightseeing",
    "tour",
    "explore",
    "khám phá",

    // ===== GỢI Ý & LỘ TRÌNH =====
    "gợi ý",
    "recommend",
    "suggestion",
    "đề xuất",
    "tư vấn",
    "advice",
    "lộ trình",
    "itinerary",
    "hành trình",
    "lịch trình",
    "schedule",
    "kế hoạch",
    "plan",
    "route",
    "journey",
    "trip",
    "travel plan",
    "tour guide",

    // ===== ĐẶC ĐIỂM ĐỊA ĐIỂM =====
    "nổi tiếng",
    "famous",
    "popular",
    "phổ biến",
    "hot",
    "trending",
    "đẹp",
    "beautiful",
    "scenic",
    "picturesque",
    "đẹp nhất",
    "best",
    "view đẹp",
    "nice view",
    "sống ảo",
    "instagrammable",
    "check in",
    "checkin",
    "chụp ảnh",
    "photo spot",
    "photography",
    "selfie",
    "backdrop",
    "must see",
    "must visit",
    "không thể bỏ lỡ",
    "nên đi",
    "đáng đi",

    // ===== ĂN UỐNG =====
    "ăn",
    "eat",
    "ăn uống",
    "food",
    "dining",
    "meal",
    "quán ăn",
    "restaurant",
    "nhà hàng",
    "dining",
    "eatery",
    "bistro",
    "quán",
    "shop",
    "store",
    "quán cà phê",
    "cafe",
    "coffee",
    "cà phê",
    "quán nước",
    "drink shop",
    "tea house",
    "trà",
    "tea",
    "bar",
    "pub",
    "club",
    "nightclub",
    "karaoke",
    "lounge",
    "buffet",
    "bbq",
    "nướng",
    "lẩu",
    "hotpot",
    "phở",
    "bún",
    "cơm",
    "hải sản",
    "seafood",
    "fish",
    "cua",
    "tôm",
    "ốc",
    "sushi",
    "món ngon",
    "delicious",
    "đặc sản",
    "specialty",
    "local food",
    "street food",
    "ăn vặt",
    "snack",
    "dessert",
    "tráng miệng",
    "ice cream",
    "kem",
    "breakfast",
    "bữa sáng",
    "lunch",
    "bữa trưa",
    "dinner",
    "bữa tối",

    // ===== MUA SẮM =====
    "mua sắm",
    "shopping",
    "shop",
    "chợ",
    "market",
    "siêu thị",
    "supermarket",
    "mall",
    "trung tâm thương mại",
    "department store",
    "convenience store",
    "boutique",
    "souvenir",
    "quà lưu niệm",
    "gift shop",

    // ===== THIÊN NHIÊN =====
    "biển",
    "beach",
    "bãi biển",
    "seaside",
    "coast",
    "bờ biển",
    "núi",
    "mountain",
    "đồi",
    "hill",
    "đỉnh",
    "peak",
    "summit",
    "sông",
    "river",
    "hồ",
    "lake",
    "suối",
    "stream",
    "thác",
    "waterfall",
    "rừng",
    "forest",
    "jungle",
    "cave",
    "hang động",
    "grotto",
    "đảo",
    "island",
    "peninsula",
    "bán đảo",
    "bay",
    "vịnh",
    "công viên",
    "park",
    "vườn",
    "garden",
    "botanical",
    "thực vật",

    // ===== VĂN HÓA & TÔN GIÁO =====
    "chùa",
    "pagoda",
    "temple",
    "đền",
    "shrine",
    "linh thiêng",
    "sacred",
    "nhà thờ",
    "church",
    "cathedral",
    "chapel",
    "nhà thờ đức bà",
    "đình",
    "communal house",
    "miếu",
    "văn miếu",

    // ===== BẢO TÀNG & VĂN HÓA =====
    "bảo tàng",
    "museum",
    "gallery",
    "triển lãm",
    "exhibition",
    "lịch sử",
    "history",
    "văn hóa",
    "culture",
    "heritage",
    "di sản",
    "cổ kính",
    "ancient",
    "traditional",
    "truyền thống",

    // ===== GIẢI TRÍ & VUI CHƠI =====
    "vui chơi",
    "entertainment",
    "fun",
    "activity",
    "hoạt động",
    "khu vui chơi",
    "amusement park",
    "theme park",
    "water park",
    "công viên nước",
    "resort",
    "spa",
    "massage",
    "thư giãn",
    "relax",
    "wellness",
    "gym",
    "yoga",
    "fitness",
    "thể thao",
    "sport",
    "golf",
    "tennis",
    "bơi",
    "swimming",
    "pool",
    "hồ bơi",
    "diving",
    "lặn",
    "snorkeling",
    "cinema",
    "rạp phim",
    "movie",
    "theater",
    "show",
    "concert",
    "live music",

    // ===== ĐỊA DANH ĐÀ NẴNG CỤ THỂ =====
    "đà nẵng",
    "da nang",
    "danang",
    "bà nà",
    "ba na",
    "bana",
    "bana hills",
    "bà nà hills",
    "cầu vàng",
    "golden bridge",
    "golden hands bridge",
    "sơn trà",
    "son tra",
    "bán đảo sơn trà",
    "son tra peninsula",
    "linh ứng",
    "linh ung",
    "chùa linh ứng",
    "lady buddha",
    "mỹ khê",
    "my khe",
    "mỹ an",
    "my an",
    "bãi biển mỹ khê",
    "non nước",
    "non nuoc",
    "bãi non nước",
    "ngũ hành sơn",
    "ngu hanh son",
    "marble mountains",
    "núi đá",
    "hội an",
    "hoi an",
    "phố cổ",
    "old town",
    "ancient town",
    "cầu nhật bản",
    "japanese bridge",
    "cầu pagoda",
    "phố cổ hội an",
    "hoi an ancient town",
    "huế",
    "hue",
    "kinh thành",
    "citadel",
    "đại nội",
    "imperial city",
    "lăng",
    "tomb",
    "lăng tự đức",
    "lăng khải định",
    "asia park",
    "sun wheel",
    "vòng quay mặt trời",
    "cầu rồng",
    "dragon bridge",
    "cầu sông hàn",
    "han river bridge",
    "bảo tàng chăm",
    "cham museum",
    "cham sculpture museum",
    "bãi rạng",
    "nam ô",
    "nam o",
    "bãi nam ô",

    // ===== THỜI GIAN =====
    "sáng",
    "morning",
    "buổi sáng",
    "trưa",
    "noon",
    "afternoon",
    "buổi trưa",
    "chiều",
    "evening",
    "buổi chiều",
    "tối",
    "night",
    "ban đêm",
    "buổi tối",
    "ngày",
    "day",
    "ban ngày",
    "daytime",
    "đêm",
    "nighttime",
    "overnight",
    "1 ngày",
    "one day",
    "half day",
    "nửa ngày",
    "full day",
    "2 ngày",
    "two days",
    "3 ngày",
    "three days",
    "tuần",
    "week",
    "hôm nay",
    "today",
    "ngày mai",
    "tomorrow",
    "cuối tuần",
    "weekend",

    // ===== ĐỐI TƯỢNG =====
    "gia đình",
    "family",
    "family-friendly",
    "trẻ em",
    "kids",
    "children",
    "cặp đôi",
    "couple",
    "romantic",
    "lãng mạn",
    "honeymoon",
    "hưởng tuần trăng mật",
    "một mình",
    "solo",
    "single",
    "backpacker",
    "dã ngoại",
    "nhóm",
    "group",
    "bạn bè",
    "friends",
    "đoàn",
    "team",
    "người già",
    "elderly",
    "senior",

    // ===== KHOẢNG CÁCH =====
    "xa",
    "far",
    "gần nhất",
    "nearest",
    "closest",
    "gần đây",
    "around here",
    "trong vòng",
    "within",
    "bán kính",
    "radius",
    "km",
    "kilometer",
    "cách",
    "distance",
    "khoảng cách",
    "how far",
    "bao xa",
    "đi bộ",
    "walking",
    "walk",
    "đi xe",
    "drive",
    "driving",
    "taxi",
    "grab",

    // ===== ĐỊA CHỈ & ĐƯỜNG =====
    "đường",
    "street",
    "road",
    "avenue",
    "phố",
    "lane",
    "alley",
    "quận",
    "district",
    "huyện",
    "county",
    "phường",
    "ward",
    "khu",
    "area",
    "zone",
    "region",
    "vùng",
    "miền",

    // ===== NIGHTLIFE =====
    "nightlife",
    "đi bar",
    "đi club",
    "bar hopping",
    "party",
    "tiệc",
    "bia",
    "beer",
    "rượu",
    "wine",
    "cocktail",
    "mocktail",
    "live music",
    "nhạc sống",
    "dj",
    "dance",
    "nhảy",

    // ===== HOẠT ĐỘNG ĐẶC BIỆT =====
    "lướt ván",
    "surfing",
    "surf",
    "kitesurfing",
    "windsurf",
    "chèo thuyền",
    "kayak",
    "canoeing",
    "boat",
    "thuyền",
    "câu cá",
    "fishing",
    "scuba diving",
    "lặn biển",
    "leo núi",
    "climbing",
    "hiking",
    "trekking",
    "đi bộ đường dài",
    "dù lượn",
    "paragliding",
    "skydiving",
    "zipline",
    "cooking class",
    "lớp nấu ăn",
    "workshop",
  ];

  if (nearbyKeywords.some((keyword) => msg.includes(keyword))) {
    return "nearby";
  }

  // ========================================
  // 3️⃣ KIỂM TRA TỪ KHÓA VỀ THỜI TIẾT
  // ========================================
  const weatherKeywords = [
    "thời tiết",
    "weather",
    "forecast",
    "dự báo",
    "nắng",
    "sunny",
    "sun",
    "có nắng",
    "trời nắng",
    "mưa",
    "rain",
    "rainy",
    "có mưa",
    "trời mưa",
    "mưa không",
    "nhiệt độ",
    "temperature",
    "temp",
    "độ",
    "bao nhiêu độ",
    "trời",
    "sky",
    "weather condition",
    "tình trạng",
    "khí hậu",
    "climate",
    "nóng",
    "hot",
    "lạnh",
    "cold",
    "warm",
    "cool",
    "ấm",
    "mát",
    "gió",
    "wind",
    "windy",
    "có gió",
    "bão",
    "storm",
    "stormy",
    "ẩm",
    "humid",
    "humidity",
    "độ ẩm",
    "khô",
    "dry",
    "sương mù",
    "fog",
    "foggy",
    "mist",
    "misty",
    "tuyết",
    "snow",
    "snowy",
    "hôm nay",
    "today",
    "ngày mai",
    "tomorrow",
    "tomorrow weather",
    "cuối tuần",
    "weekend",
    "tuần sau",
    "next week",
    "như thế nào",
    "how is",
    "ra sao",
  ];

  if (weatherKeywords.some((keyword) => msg.includes(keyword))) {
    return "weather";
  }

  // ========================================
  // 4️⃣ KIỂM TRA TỪ KHÓA VỀ KHÁCH SẠN
  // ========================================
  const hotelKeywords = [
    // Thông tin cơ bản
    "khách sạn",
    "hotel",
    "resort",
    "accommodation",
    "nơi ở",
    "thông tin",
    "info",
    "information",
    "about",
    "giới thiệu",
    "introduction",

    // Vị trí
    "ở đâu",
    "where",
    "location",
    "vị trí",
    "địa chỉ",
    "address",
    "cách",
    "far from",
    "xa",
    "gần",

    // Check in/out
    "check in",
    "checkin",
    "check out",
    "checkout",
    "giờ",
    "time",
    "mấy giờ",
    "what time",
    "when",
    "sớm",
    "early",
    "muộn",
    "late",
    "late checkout",
    "early checkin",

    // Chính sách
    "chính sách",
    "policy",
    "policies",
    "quy định",
    "rules",
    "regulation",
    "hủy",
    "cancel",
    "cancellation",
    "hủy phòng",
    "refund",
    "hoàn tiền",
    "đặt cọc",
    "deposit",
    "prepay",
    "trả trước",

    // Thanh toán
    "thanh toán",
    "payment",
    "pay",
    "paying",
    "how to pay",
    "thẻ",
    "card",
    "credit card",
    "debit card",
    "visa",
    "mastercard",
    "tiền mặt",
    "cash",
    "chuyển khoản",
    "transfer",
    "banking",
    "bank transfer",
    "ví điện tử",
    "e-wallet",
    "momo",
    "zalopay",
    "vnpay",

    // Tiện nghi
    "tiện nghi",
    "amenities",
    "facilities",
    "tiện ích",
    "dịch vụ",
    "service",
    "wifi",
    "internet",
    "wi-fi",
    "wireless",
    "parking",
    "bãi đỗ xe",
    "chỗ đỗ xe",
    "đậu xe",
    "hồ bơi",
    "pool",
    "swimming pool",
    "bể bơi",
    "gym",
    "fitness",
    "fitness center",
    "phòng gym",
    "spa",
    "massage",
    "sauna",
    "jacuzzi",
    "steam room",
    "nhà hàng",
    "restaurant",
    "dining",
    "ăn uống",
    "bar",
    "minibar",
    "mini bar",
    "mini fridge",
    "tủ lạnh",
    "breakfast",
    "bữa sáng",
    "buffet",
    "ăn sáng",
    "room service",
    "dịch vụ phòng",
    "laundry",
    "giặt ủi",
    "giặt là",
    "dry cleaning",

    // Di chuyển
    "đưa đón",
    "shuttle",
    "pickup",
    "đón",
    "送迎",
    "airport",
    "sân bay",
    "airport transfer",
    "đưa đón sân bay",
    "taxi",
    "grab",
    "xe",
    "car",
    "transportation",
    "phương tiện",

    // An ninh & An toàn
    "an ninh",
    "security",
    "safe",
    "két sắt",
    "safety box",
    "camera",
    "cctv",
    "bảo vệ",
    "security guard",

    // Thú cưng
    "thú cưng",
    "pet",
    "pets",
    "dog",
    "cat",
    "chó",
    "mèo",
    "pet-friendly",
    "cho phép thú cưng",
    "mang thú cưng",

    // Trẻ em
    "trẻ em",
    "children",
    "kids",
    "baby",
    "em bé",
    "infant",
    "cũi",
    "crib",
    "baby cot",
    "giường em bé",
    "giường phụ",
    "extra bed",
    "additional bed",
    "babysitter",
    "người trông trẻ",

    // Khác
    "khăn",
    "towel",
    "bath towel",
    "dép",
    "slippers",
    "sandals",
    "áo choàng",
    "bathrobe",
    "robe",
    "đồ vệ sinh",
    "toiletries",
    "amenity kit",
    "tv",
    "television",
    "cable",
    "netflix",
    "air conditioner",
    "điều hòa",
    "ac",
    "máy lạnh",
    "heater",
    "nóng lạnh",
    "water heater",
    "bình nóng lạnh",
    "view",
    "cửa sổ",
    "window",
    "balcony",
    "ban công",
    "smoking",
    "hút thuốc",
    "non-smoking",
    "không hút thuốc",
    "accessible",
    "wheelchair",
    "xe lăn",
    "người khuyết tật",
    "disabled",
    "elevator",
    "thang máy",
    "lift",
    "reception",
    "lễ tân",
    "front desk",
    "concierge",
    "housekeeping",
    "dọn phòng",
    "cleaning",
  ];

  if (hotelKeywords.some((keyword) => msg.includes(keyword))) {
    return "hotel_info";
  }

  // ========================================
  // 5️⃣ CHÀO HỎI & CÂU HỎI CHUNG
  // ========================================
  const generalKeywords = [
    // Chào hỏi
    "xin chào",
    "chào",
    "hello",
    "hi",
    "hey",
    "greetings",
    "good morning",
    "good afternoon",
    "good evening",
    "good night",
    "chào buổi sáng",
    "chào buổi chiều",
    "chào buổi tối",

    // Cảm ơn
    "cảm ơn",
    "thank",
    "thanks",
    "thank you",
    "cảm ơn bạn",
    "thanks a lot",
    "thank you so much",
    "cám ơn",

    // Tạm biệt
    "tạm biệt",
    "bye",
    "goodbye",
    "see you",
    "see ya",
    "good bye",
    "hẹn gặp lại",
    "talk to you later",

    // Câu hỏi về bot
    "bạn là ai",
    "you are",
    "who are you",
    "ai",
    "who",
    "bạn có thể làm gì",
    "what can you do",
    "giúp gì",

    // Yêu cầu trợ giúp
    "giúp",
    "help",
    "hỗ trợ",
    "support",
    "assist",
    "assistance",
    "giúp tôi",
    "help me",
    "can you help",

    // Câu hỏi chung
    "có thể",
    "can you",
    "bạn có thể",
    "could you",
    "tôi muốn",
    "i want",
    "i need",
    "tôi cần",
    "i would like",
    "làm ơn",
    "please",
    "xin vui lòng",
  ];

  if (generalKeywords.some((keyword) => msg.includes(keyword))) {
    return "general";
  }

  // ========================================
  // 6️⃣ MẶC ĐỊNH
  // ========================================
  return "general";
}
