export const PERMISSIONS = {
  // Booking
  BOOKING_READ: "BOOKING_READ",
  BOOKING_CREATE: "BOOKING_CREATE",
  BOOKING_UPDATE: "BOOKING_UPDATE",
  BOOKING_DELETE: "BOOKING_DELETE",
  // Customer
  CUSTOMER_READ: "CUSTOMER_READ",
  CUSTOMER_CREATE: "CUSTOMER_CREATE",
  CUSTOMER_UPDATE: "CUSTOMER_UPDATE",
  CUSTOMER_DELETE: "CUSTOMER_DELETE",
  // Room
  ROOM_READ: "ROOM_READ",
  ROOM_CREATE: "ROOM_CREATE",
  ROOM_UPDATE: "ROOM_UPDATE",
  ROOM_DELETE: "ROOM_DELETE",
  // Room Type
  ROOM_TYPE_READ: "ROOM_TYPE_READ",
  ROOM_TYPE_CREATE: "ROOM_TYPE_CREATE",
  ROOM_TYPE_UPDATE: "ROOM_TYPE_UPDATE",
  ROOM_TYPE_DELETE: "ROOM_TYPE_DELETE",
  // Seasonal Rate
  SEASONAL_RATE_READ: "SEASONAL_RATE_READ",
  SEASONAL_RATE_CREATE: "SEASONAL_RATE_CREATE",
  SEASONAL_RATE_UPDATE: "SEASONAL_RATE_UPDATE",
  SEASONAL_RATE_DELETE: "SEASONAL_RATE_DELETE",
  // Maintenance
  MAINTENANCE_READ: "MAINTENANCE_READ",
  MAINTENANCE_UPDATE: "MAINTENANCE_UPDATE",
  // Payment
  PAYMENT_READ: "PAYMENT_READ",
  PAYMENT_CREATE: "PAYMENT_CREATE",
  PAYMENT_UPDATE: "PAYMENT_UPDATE",
  // Review
  REVIEW_READ: "REVIEW_READ",
  REVIEW_DELETE: "REVIEW_DELETE",
  // Discount
  DISCOUNT_READ: "DISCOUNT_READ",
  DISCOUNT_CREATE: "DISCOUNT_CREATE",
  DISCOUNT_UPDATE: "DISCOUNT_UPDATE",
  DISCOUNT_DELETE: "DISCOUNT_DELETE",
  // Blog
  BLOG_READ: "BLOG_READ",
  BLOG_CREATE: "BLOG_CREATE",
  BLOG_UPDATE: "BLOG_UPDATE",
  BLOG_DELETE: "BLOG_DELETE",
  // User
  USER_READ: "USER_READ",
  USER_CREATE: "USER_CREATE",
  USER_UPDATE: "USER_UPDATE",
  USER_DELETE: "USER_DELETE",
  // Role & Report
  ROLE_MANAGE: "ROLE_MANAGE",
  REPORT_VIEW: "REPORT_VIEW",
  // Audit Log
  AUDIT_LOG_READ: "AUDIT_LOG_READ",
};
